// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxzGh5PKoKVt9L_EFZ7Oq5gb-RSscE_U',
    appId: '1:98875422640:web:533ce89cbab7ce53f20875',
    messagingSenderId: '98875422640',
    projectId: 'safariox',
    authDomain: 'safariox.firebaseapp.com',
    storageBucket: 'safariox.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL1fPR17heEDPasye4SjgJzWYWrD6tMUw',
    appId: '1:98875422640:android:54a2037f64281f4ff20875',
    messagingSenderId: '98875422640',
    projectId: 'safariox',
    storageBucket: 'safariox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPL-DgIStQg6A8Na6zX7W4pg88598Fb0',
    appId: '1:98875422640:ios:20167228f9350107f20875',
    messagingSenderId: '98875422640',
    projectId: 'safariox',
    storageBucket: 'safariox.firebasestorage.app',
    androidClientId: '98875422640-ej5tnuem46abvur1788063m4khauhp2o.apps.googleusercontent.com',
    iosClientId: '98875422640-o0s9d4184gga818e7menmdm65c9dkcif.apps.googleusercontent.com',
    iosBundleId: 'com.example.safariox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPL-DgIStQg6A8Na6zX7W4pg88598Fb0',
    appId: '1:98875422640:ios:20167228f9350107f20875',
    messagingSenderId: '98875422640',
    projectId: 'safariox',
    storageBucket: 'safariox.firebasestorage.app',
    androidClientId: '98875422640-ej5tnuem46abvur1788063m4khauhp2o.apps.googleusercontent.com',
    iosClientId: '98875422640-o0s9d4184gga818e7menmdm65c9dkcif.apps.googleusercontent.com',
    iosBundleId: 'com.example.safariox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxzGh5PKoKVt9L_EFZ7Oq5gb-RSscE_U',
    appId: '1:98875422640:web:c8a6f0ae8216b296f20875',
    messagingSenderId: '98875422640',
    projectId: 'safariox',
    authDomain: 'safariox.firebaseapp.com',
    storageBucket: 'safariox.firebasestorage.app',
  );
}
